### ISSUE TITLE
[Feature]: Implement appbar feature

### ISSUE THREAD

**Issue by divyamD13** [OPCODE-Open-Spring-Fest/virtual_dice_roll#1]
### So, what is it about?

Design an Appbar for the home page. The Appbar should contain the name of app and a drawer button. Customise the Appbar accordingly.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ayushcodes0** [comment]
Sir, I want to contribute on this 
please assign it to me

**Comment by divyamD13** [comment]
Issue resolved
