### ISSUE TITLE
[Bug]: Fix the button onpressed feature

### ISSUE THREAD

**Issue by divyamD13** [OPCODE-Open-Spring-Fest/virtual_dice_roll#3]
### Description

In the home page after clicking on the button the new dice number is not generated.

### Severity

Medium

### Steps to reproduce

1. Click on the 'Roll' button.
2. The new dice number is not generated.

 

### Environment

OS: Android/ios
Browser: all
Language:Dart

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ayushcodes0** [comment]
Sir please assign this task to me.

**Comment by divyamD13** [comment]
issue resolved
